-- Migración: cuenta bi-moneda Banco Santander + seña con moneda/cuenta.
-- Correr en el SQL editor de Supabase (proyecto kbxcrijyftndbnqftxhw), schema public.
-- Son sentencias aditivas y seguras (solo CREATE/ALTER de objetos de Ruca).
-- NO toca el schema z_fp. Se puede correr este archivo entero de una.

CREATE TABLE IF NOT EXISTS cuenta_movimientos (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date         DATE NOT NULL,
    account      TEXT NOT NULL DEFAULT 'Santander',
    kind         TEXT NOT NULL CHECK (kind IN ('apertura','ingreso','egreso','fx')),
    delta_ars    NUMERIC NOT NULL DEFAULT 0,   -- + entra, - sale
    delta_usd    NUMERIC NOT NULL DEFAULT 0,
    description  TEXT,
    notes        TEXT,
    cancelled_at TIMESTAMPTZ,                  -- soft-delete (nunca DELETE)
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE reservations ADD COLUMN IF NOT EXISTS deposit_account  TEXT;
ALTER TABLE reservations ADD COLUMN IF NOT EXISTS deposit_currency TEXT DEFAULT 'USD';
ALTER TABLE reservations ADD COLUMN IF NOT EXISTS deposit_ars      NUMERIC;

-- RLS: misma postura que el resto de tablas Ruca (habilitado, sin policies →
-- el rol postgres/owner que usa la app la bypassa; el acceso anónimo queda cerrado).
ALTER TABLE cuenta_movimientos ENABLE ROW LEVEL SECURITY;
