-- Ruca Eden finance DB — Postgres schema (port of ../../sql/schema.sql)
-- Source of truth during transition: the Google Sheet, via ruca.db + etl/push_supabase.py
-- (truncate+reload). ids are preserved from SQLite via OVERRIDING SYSTEM VALUE.

DROP VIEW IF EXISTS v_future_reservations, v_booking_alerts, v_revenue_by_platform,
                    v_occupancy, v_pagos_fijos_sheet, v_pagos_fijos, v_monthly_summary CASCADE;
DROP TABLE IF EXISTS entregas, tx_links, res_cobradas, res_invitaciones, attribution_overrides,
                     reservation_nights, transactions, reservations, category_map,
                     warnings CASCADE;

CREATE TABLE reservations (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    checkin         DATE NOT NULL,
    checkout        DATE NOT NULL,
    guest_name      TEXT,
    phone           TEXT,
    cabin           TEXT,               -- Alerce/Coihue(viejo:Cohiue)/Maiten/Ruca/Ruca Chico/Ruqui/TODAS
    platform        TEXT,               -- AirBnb/WA/Meli/Booking/Instagram/Parairnos/Terceros
    nights          INTEGER,
    price_per_night NUMERIC,
    total_usd       NUMERIC,
    deposit_usd     NUMERIC,
    balance_usd     NUMERIC,
    payment_method  TEXT,
    collected       SMALLINT,           -- 1/0/NULL (sheet checkbox)
    who_has_money   TEXT,
    flag            TEXT,               -- sheet col P (legacy; superseded by v_booking_alerts)
    notes           TEXT,
    source_row      INTEGER,
    cancelled_at    TIMESTAMPTZ         -- NULL = activa; fecha = cancelada (soft-delete, nunca borrar)
);

CREATE TABLE reservation_nights (
    reservation_id  BIGINT REFERENCES reservations(id) ON DELETE CASCADE,
    night           DATE NOT NULL,
    cabin           TEXT,
    rate_usd        NUMERIC
);

CREATE TABLE transactions (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind                TEXT NOT NULL CHECK (kind IN ('ingreso','egreso')),
    date                DATE NOT NULL,
    description         TEXT,
    amount_ars          NUMERIC,
    amount_usd          NUMERIC,
    blue_rate           NUMERIC,
    category_raw        TEXT,
    category            TEXT,
    payment_method_raw  TEXT,
    payment_method      TEXT,
    cabin               TEXT,
    invoice_url         TEXT,
    notes               TEXT,
    source_sheet        TEXT NOT NULL,
    source_row          INTEGER,
    reservation_id      BIGINT REFERENCES reservations(id) ON DELETE SET NULL,
    holder              TEXT,               -- quién tiene la plata (Mica/Gustavo/…)
    currency            TEXT DEFAULT 'USD'  -- moneda nativa del ingreso: 'USD' | 'ARS' (pesos)
);

-- Entregas de plata de un holder a Mimi (baja el contador "X tiene USD$…").
-- Pueden ir atadas a un cobro puntual (transaction_id) o sueltas (NULL). Moneda
-- 'USD' o 'ARS' (en pesos usa amount_ars). Soft-delete con cancelled_at.
CREATE TABLE entregas (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date           DATE NOT NULL,
    holder         TEXT NOT NULL,
    amount_usd     NUMERIC,                 -- monto si currency='USD' (o equiv. USD)
    currency       TEXT DEFAULT 'USD',      -- 'USD' | 'ARS'
    amount_ars     NUMERIC,                 -- monto si currency='ARS'
    transaction_id BIGINT REFERENCES transactions(id),  -- cobro atado (NULL = entrega suelta)
    cancelled_at   TIMESTAMPTZ,             -- soft-delete (nunca DELETE)
    notes          TEXT
);

-- Vínculo reserva <-> ingreso de la PLANILLA, por identidad estable (sheet, row).
-- Sobrevive al truncate+reload del push (re-aplicado por push_supabase.py).
CREATE TABLE tx_links (
    reservation_id  BIGINT,
    source_sheet    TEXT,
    source_row      INTEGER,
    PRIMARY KEY (source_sheet, source_row)
);

-- Reservas marcadas como cobradas desde la app (la planilla no se entera).
CREATE TABLE res_cobradas (
    reservation_id  BIGINT PRIMARY KEY
);

-- Invitados: reservas que nunca se cobran a propósito (amigos/familia).
CREATE TABLE res_invitaciones (
    reservation_id  BIGINT PRIMARY KEY
);

-- Overrides quirúrgicos de imputación: gastos puntuales cuya celda en la
-- planilla no sigue la convención general (ej. Agua/Gas de ene-2025 que la
-- planilla deja en enero en vez de correr a diciembre). Sobrevive al push.
CREATE TABLE attribution_overrides (
    source_sheet  TEXT,
    source_row    INTEGER,
    mes           TEXT NOT NULL,   -- 'YYYY-MM'
    PRIMARY KEY (source_sheet, source_row)
);

CREATE TABLE category_map (
    canonical    TEXT PRIMARY KEY,
    month_shift  INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE warnings (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_sheet TEXT,
    source_row   INTEGER,
    message      TEXT
);

CREATE INDEX idx_tx_date ON transactions(date);
CREATE INDEX idx_tx_cat  ON transactions(category);
CREATE INDEX idx_rn_night ON reservation_nights(night);

-- ── Calendario externo (agregado 2026-06-12) ────────────────────────────────
-- Fuentes de calendario externas: Google Calendar (1 URL iCal secreta, todas las
-- cabañas) + Airbnb (1 URL iCal por cabaña). Solo lectura, para el chequeo
-- cruzado contra las reservas de la app. Soft-delete con `active` (nunca DELETE).
-- ⚠️ Aplicar SOLO esta sentencia en Supabase — nunca correr el archivo entero
--    (los DROP de arriba borrarían todo). Tabla de Ruca, en schema public.
CREATE TABLE calendar_sources (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind        TEXT NOT NULL CHECK (kind IN ('google','airbnb')),
    label       TEXT,            -- "Google (todas)", "Airbnb Alerce"
    cabin       TEXT,            -- NULL para google; cabaña (no 'TODAS') para airbnb
    ics_url     TEXT NOT NULL,   -- URL secreta del feed (solo lectura)
    active      BOOLEAN NOT NULL DEFAULT true,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_calsrc_active ON calendar_sources(active);

-- ── Links de contratos JotForm (agregado 2026-06-13) ────────────────────────
-- Acortador propio: guarda la URL larga de prellenado de JotForm con un código
-- corto, para mandarle al inquilino un link corto (<app>/c/<code>) que redirige.
-- Sin borrado (queda historial). ⚠️ Aplicar SOLO esta sentencia. Ruca, public.
CREATE TABLE contract_links (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code       TEXT NOT NULL UNIQUE,
    url        TEXT NOT NULL,
    guest      TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ── Cuenta bancaria bi-moneda (Banco Santander) (agregado 2026-06-25) ────────
-- Libro mayor de la cuenta que Mimi usa para alquileres (señas que le pagan,
-- gastos que paga). Lleva pesos y USD a la vez. `delta_*` positivo = entra,
-- negativo = sale. Esta tabla SOLO guarda lo que no está en otras tablas:
--   apertura (saldo inicial), compra/venta de USD (fx, libre, sin dólar blue) y
--   movimientos manuales. Las señas de reservas (deposit_account='Santander') y
--   los egresos con payment_method='Santander' se suman/restan en las lecturas
--   (src/db/cuenta.ts), no se duplican acá. Soft-delete con `cancelled_at`.
-- ⚠️ Aplicar SOLO esta sentencia en Supabase — nunca el archivo entero. Ruca, public.
CREATE TABLE cuenta_movimientos (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date         DATE NOT NULL,
    account      TEXT NOT NULL DEFAULT 'Santander',
    kind         TEXT NOT NULL CHECK (kind IN ('apertura','ingreso','egreso','fx')),
    delta_ars    NUMERIC NOT NULL DEFAULT 0,   -- + entra, - sale
    delta_usd    NUMERIC NOT NULL DEFAULT 0,
    description  TEXT,
    notes        TEXT,
    cancelled_at TIMESTAMPTZ,                  -- soft-delete (nunca DELETE)
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Seña con moneda + cuenta en cada reserva (agregado 2026-06-25).
-- deposit_usd se mantiene como hoy (seña en USD); si la seña es en pesos se usa
-- deposit_ars y deposit_usd queda NULL (no toca balance_usd, son cuentas aparte).
-- ⚠️ Aplicar SOLO estas 3 sentencias en Supabase. Ruca, public.
ALTER TABLE reservations ADD COLUMN deposit_account  TEXT;                  -- 'Cash'/'Santander'/libre
ALTER TABLE reservations ADD COLUMN deposit_currency TEXT DEFAULT 'USD';    -- 'USD' | 'ARS'
ALTER TABLE reservations ADD COLUMN deposit_ars      NUMERIC;               -- monto de la seña si es en pesos
